export { RealTaskHarness, type RecoveryProposerMode } from './RealTaskHarness';
export type {
  RealTask,
  RealTaskDomain,
  RealTaskSuccessCriteria,
  RealTaskResult,
  RealTaskReport,
  RealTaskMetrics,
  RealTaskEvidenceChain,
  RealTaskStepRecord,
  TaskEnvironment,
} from './RealTaskTypes';
export {
  T01_FileCreate,
  T02_FileModify,
  T03_FileFindAndSummarize,
  T04_BrowserSearch,
  T05_WebFetchAndSave,
  T06_CodeModify,
  T07_RunTest,
  T08_TestFailAndFix,
  T09_EnvironmentChangeReplan,
  T10_MultiStepTask,
  G1_MulInsteadOfAdd,
  G2_OffByOne,
  G3_UnknownPathMissing,
  G4_NestedDirMissing,
  G5_ConfigError,
  G6_TwoStageError,
  G7_TypeCoercion,
  G8_MissingAwait,
  G9_FilePermission,
  G10_MissingEnvVar,
  G11_LoopConditionInverted,
  G12_BomEncoding,
  N1_ConfigTypo,
  N2_DataTransform,
  N3_UnknownDirRestore,
  N4_TestSetupFix,
  N5_CrossFileDep,
  ALL_REAL_TASKS,
} from './RealTasks';
