"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PanelSkeleton = void 0;
const jsx_runtime_1 = require("react/jsx-runtime");
require("./PanelSkeleton.css");
const PanelSkeleton = ({ statsCount = 0, sectionCount = 2, rowsPerSection = 3, hasTabs = false, tabCount = 3, }) => {
    return ((0, jsx_runtime_1.jsxs)("div", { className: "panel-skeleton", children: [(0, jsx_runtime_1.jsxs)("div", { className: "panel-skeleton__header", children: [(0, jsx_runtime_1.jsx)("div", { className: "panel-skeleton__title" }), (0, jsx_runtime_1.jsx)("div", { className: "panel-skeleton__subtitle" })] }), hasTabs && ((0, jsx_runtime_1.jsx)("div", { className: "panel-skeleton__tabs", children: Array.from({ length: tabCount }).map((_, i) => ((0, jsx_runtime_1.jsx)("div", { className: "panel-skeleton__tab" }, i))) })), statsCount > 0 && ((0, jsx_runtime_1.jsx)("div", { className: "panel-skeleton__stats", children: Array.from({ length: statsCount }).map((_, i) => ((0, jsx_runtime_1.jsxs)("div", { className: "panel-skeleton__stat-card", children: [(0, jsx_runtime_1.jsx)("div", { className: "panel-skeleton__stat-value" }), (0, jsx_runtime_1.jsx)("div", { className: "panel-skeleton__stat-label" })] }, i))) })), Array.from({ length: sectionCount }).map((_, si) => ((0, jsx_runtime_1.jsxs)("div", { className: "panel-skeleton__section", children: [(0, jsx_runtime_1.jsx)("div", { className: "panel-skeleton__section-title" }), Array.from({ length: rowsPerSection }).map((_, ri) => ((0, jsx_runtime_1.jsxs)("div", { className: "panel-skeleton__row", children: [(0, jsx_runtime_1.jsx)("div", { className: "panel-skeleton__label" }), (0, jsx_runtime_1.jsx)("div", { className: "panel-skeleton__input" })] }, ri))), (0, jsx_runtime_1.jsxs)("div", { className: "panel-skeleton__actions", children: [(0, jsx_runtime_1.jsx)("div", { className: "panel-skeleton__btn panel-skeleton__btn--primary" }), (0, jsx_runtime_1.jsx)("div", { className: "panel-skeleton__btn" })] })] }, si)))] }));
};
exports.PanelSkeleton = PanelSkeleton;
exports.default = exports.PanelSkeleton;
