"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ALL_REAL_TASKS = exports.G6_TwoStageError = exports.G5_ConfigError = exports.G4_NestedDirMissing = exports.G3_UnknownPathMissing = exports.G2_OffByOne = exports.G1_MulInsteadOfAdd = exports.T10_MultiStepTask = exports.T09_EnvironmentChangeReplan = exports.T08_TestFailAndFix = exports.T07_RunTest = exports.T06_CodeModify = exports.T05_WebFetchAndSave = exports.T04_BrowserSearch = exports.T03_FileFindAndSummarize = exports.T02_FileModify = exports.T01_FileCreate = exports.RealTaskHarness = void 0;
var RealTaskHarness_1 = require("./RealTaskHarness");
Object.defineProperty(exports, "RealTaskHarness", { enumerable: true, get: function () { return RealTaskHarness_1.RealTaskHarness; } });
var RealTasks_1 = require("./RealTasks");
Object.defineProperty(exports, "T01_FileCreate", { enumerable: true, get: function () { return RealTasks_1.T01_FileCreate; } });
Object.defineProperty(exports, "T02_FileModify", { enumerable: true, get: function () { return RealTasks_1.T02_FileModify; } });
Object.defineProperty(exports, "T03_FileFindAndSummarize", { enumerable: true, get: function () { return RealTasks_1.T03_FileFindAndSummarize; } });
Object.defineProperty(exports, "T04_BrowserSearch", { enumerable: true, get: function () { return RealTasks_1.T04_BrowserSearch; } });
Object.defineProperty(exports, "T05_WebFetchAndSave", { enumerable: true, get: function () { return RealTasks_1.T05_WebFetchAndSave; } });
Object.defineProperty(exports, "T06_CodeModify", { enumerable: true, get: function () { return RealTasks_1.T06_CodeModify; } });
Object.defineProperty(exports, "T07_RunTest", { enumerable: true, get: function () { return RealTasks_1.T07_RunTest; } });
Object.defineProperty(exports, "T08_TestFailAndFix", { enumerable: true, get: function () { return RealTasks_1.T08_TestFailAndFix; } });
Object.defineProperty(exports, "T09_EnvironmentChangeReplan", { enumerable: true, get: function () { return RealTasks_1.T09_EnvironmentChangeReplan; } });
Object.defineProperty(exports, "T10_MultiStepTask", { enumerable: true, get: function () { return RealTasks_1.T10_MultiStepTask; } });
Object.defineProperty(exports, "G1_MulInsteadOfAdd", { enumerable: true, get: function () { return RealTasks_1.G1_MulInsteadOfAdd; } });
Object.defineProperty(exports, "G2_OffByOne", { enumerable: true, get: function () { return RealTasks_1.G2_OffByOne; } });
Object.defineProperty(exports, "G3_UnknownPathMissing", { enumerable: true, get: function () { return RealTasks_1.G3_UnknownPathMissing; } });
Object.defineProperty(exports, "G4_NestedDirMissing", { enumerable: true, get: function () { return RealTasks_1.G4_NestedDirMissing; } });
Object.defineProperty(exports, "G5_ConfigError", { enumerable: true, get: function () { return RealTasks_1.G5_ConfigError; } });
Object.defineProperty(exports, "G6_TwoStageError", { enumerable: true, get: function () { return RealTasks_1.G6_TwoStageError; } });
Object.defineProperty(exports, "ALL_REAL_TASKS", { enumerable: true, get: function () { return RealTasks_1.ALL_REAL_TASKS; } });
